In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Booth_Level_Data.csv')
df

        booth_id  constituency_id  registered_voters  votes_cast
0              1              110              552.0        1886
1              2              488             1183.0        1839
2              3              438             1892.0        1263
3              4              320                NaN        1918
4              5              205             1347.0         956
...          ...              ...                ...         ...
299995    299996              431              474.0         675
299996    299997              430              210.0         806
299997    299998              345              744.0        1768
299998    299999              168              252.0        1161
299999    300000              403              215.0         939

[300000 rows x 4 columns]

In [3]:
# check this
df.isnull().sum()

booth_id                0
constituency_id         0
registered_voters    3000
votes_cast              0
dtype: int64

In [4]:
df["status"] = np.where((df["registered_voters"].isna()) | (df["votes_cast"] > df["registered_voters"]), "INVALID", "VALID")

In [5]:
df

        booth_id  constituency_id  registered_voters  votes_cast   status
0              1              110              552.0        1886  INVALID
1              2              488             1183.0        1839  INVALID
2              3              438             1892.0        1263    VALID
3              4              320                NaN        1918  INVALID
4              5              205             1347.0         956    VALID
...          ...              ...                ...         ...      ...
299995    299996              431              474.0         675  INVALID
299996    299997              430              210.0         806  INVALID
299997    299998              345              744.0        1768  INVALID
299998    299999              168              252.0        1161  INVALID
299999    300000              403              215.0         939  INVALID

[300000 rows x 5 columns]

In [17]:
df["Actual votes cast"] = np.where(df["registered_voters"].isna(), 0, df[["votes_cast","registered_voters"]].min(axis=1))

In [18]:
df

,booth_id,constituency_id,registered_voters,votes_cast,status,Actual votes cast
0,1,110,552.0,1886,INVALID,552.0
1,2,488,1183.0,1839,INVALID,1183.0
2,3,438,1892.0,1263,VALID,1263.0
3,4,320,NaN,1918,INVALID,0.0
4,5,205,1347.0,956,VALID,956.0
...,...,...,...,...,...,...
299995,299996,431,474.0,675,INVALID,474.0
299996,299997,430,210.0,806,INVALID,210.0
299997,299998,345,744.0,1768,INVALID,744.0
299998,299999,168,252.0,1161,INVALID,252.0
299999,300000,403,215.0,939,INVALID,215.0

In [19]:
df["registered_voters"] = df["registered_voters"].fillna(0).astype(int)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   booth_id           300000 non-null  int64
 1   constituency_id    300000 non-null  int64
 2   registered_voters  300000 non-null  int64
 3   votes_cast         300000 non-null  int64
 4   status             300000 non-null  object
 5   Actual votes cast  300000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 13.7+ MB

In [21]:
df["registered_voters"] = df["registered_voters"].astype("int64")

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   booth_id           300000 non-null  int64
 1   constituency_id    300000 non-null  int64
 2   registered_voters  300000 non-null  int64
 3   votes_cast         300000 non-null  int64
 4   status             300000 non-null  object
 5   Actual votes cast  300000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 13.7+ MB

# Now data is cleaned format and ready for Calculations

In [23]:
df.to_csv("cleaned_booth_data.csv", index=False)

In [26]:
# cheching

df = pd.read_csv('cleaned_booth_data.csv')
df

,booth_id,constituency_id,registered_voters,votes_cast,status,Actual votes cast
0,1,110,552,1886,INVALID,552.0
1,2,488,1183,1839,INVALID,1183.0
2,3,438,1892,1263,VALID,1263.0
3,4,320,0,1918,INVALID,0.0
4,5,205,1347,956,VALID,956.0
...,...,...,...,...,...,...
299995,299996,431,474,675,INVALID,474.0
299996,299997,430,210,806,INVALID,210.0
299997,299998,345,744,1768,INVALID,744.0
299998,299999,168,252,1161,INVALID,252.0
299999,300000,403,215,939,INVALID,215.0

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   booth_id           300000 non-null  int64
 1   constituency_id    300000 non-null  int64
 2   registered_voters  300000 non-null  int64
 3   votes_cast         300000 non-null  int64
 4   status             300000 non-null  object
 5   Actual votes cast  300000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 13.7+ MB

In [28]:
df.isnull().sum()

booth_id             0
constituency_id      0
registered_voters    0
votes_cast           0
status               0
Actual votes cast    0
dtype: int64