In [31]:
import pandas as pd
import numpy as np

In [32]:
df = pd.read_csv('Campaign_Spending.csv')
df

      campaign_id           party        state       spend        date
0               1             INC           UP  6388720.06  2025-12-09
1               2             INC   Tamil Nadu  8595779.90  2025-09-19
2               3             BJP  Maharashtra  7522730.81  2025-08-29
3               4             BJP           UP  3933796.66  2025-05-21
4               5             INC        Bihar  5618958.18  2025-04-09
...           ...             ...          ...         ...         ...
4995         4996             INC   Tamil Nadu  2729262.94  2025-11-16
4996         4997             INC  Maharashtra  1864885.56  2026-02-07
4997         4998             INC  Maharashtra  5418805.45  2026-02-03
4998         4999  Regional Party           UP    -1000.00  2025-10-10
4999         5000             BJP   Tamil Nadu  8594551.02  2026-02-09

[5000 rows x 5 columns]

In [33]:
df.isnull().sum()

campaign_id    0
party          0
state          0
spend          0
date           0
dtype: int64

In [34]:
df[df['spend'] < 0]

      campaign_id           party        state   spend        date
21             22             INC           UP -1000.0  2025-10-12
26             27             BJP  Maharashtra -1000.0  2025-07-31
49             50             INC  Maharashtra -1000.0  2025-04-29
58             59             INC        Bihar -1000.0  2026-02-13
96             97  Regional Party   Tamil Nadu -1000.0  2025-04-14
...           ...             ...          ...     ...         ...
4452         4453             INC           UP -1000.0  2026-03-30
4549         4550             AAP  Maharashtra -1000.0  2025-04-29
4731         4732             INC  Maharashtra -1000.0  2026-01-23
4813         4814             INC   Tamil Nadu -1000.0  2025-07-14
4998         4999  Regional Party           UP -1000.0  2025-10-10

[100 rows x 5 columns]

In [5]:
df.describe()

       campaign_id         spend
count  5000.000000  5.000000e+03
mean   2500.500000  4.948501e+06
std    1443.520003  2.919174e+06
min       1.000000 -1.000000e+03
25%    1250.750000  2.425384e+06
50%    2500.500000  4.975428e+06
75%    3750.250000  7.500930e+06
max    5000.000000  9.998227e+06

In [35]:
mean_val = df['spend'].mean()
mean_val

np.float64(4948501.318022)

In [36]:
df.loc[df['spend'] < 0, 'spend'] = mean_val

df

In [37]:
df[df['spend'] < 0]

Empty DataFrame
Columns: [campaign_id, party, state, spend, date]
Index: []

# now data is clean

In [39]:
df.to_csv("clean_campaign_data.csv.csv", index=False)

In [40]:
df=pd.read_csv('clean_campaign_data.csv')
df

      campaign_id           party        state         spend        date
0               1             INC           UP  6.388720e+06  2025-12-09
1               2             INC   Tamil Nadu  8.595780e+06  2025-09-19
2               3             BJP  Maharashtra  7.522731e+06  2025-08-29
3               4             BJP           UP  3.933797e+06  2025-05-21
4               5             INC        Bihar  5.618958e+06  2025-04-09
...           ...             ...          ...           ...         ...
4995         4996             INC   Tamil Nadu  2.729263e+06  2025-11-16
4996         4997             INC  Maharashtra  1.864886e+06  2026-02-07
4997         4998             INC  Maharashtra  5.418805e+06  2026-02-03
4998         4999  Regional Party           UP  4.948501e+06  2025-10-10
4999         5000             BJP   Tamil Nadu  8.594551e+06  2026-02-09

[5000 rows x 5 columns]

In [64]:
df['spend'] = df['spend'].astype(int)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   campaign_id  5000 non-null   int64
 1   party        5000 non-null   object
 2   state        5000 non-null   object
 3   spend        5000 non-null   int64
 4   date         5000 non-null   object
dtypes: int64(2), object(3)
memory usage: 195.4+ KB

In [43]:
# Partywise total spending
party_spending = df.groupby('party')['spend'].sum().reset_index()
print(party_spending)

            party       spend
0             AAP  5974583368
1             BJP  6711070320
2             INC  6242487826
3  Regional Party  6309312786

In [44]:
party_spending = party_spending.sort_values(by="spend",ascending=False)
print(party_spending)

            party       spend
1             BJP  6711070320
3  Regional Party  6309312786
2             INC  6242487826
0             AAP  5974583368

In [ ]:
# BJP had the highest campaign spending, investing approximately $6.61 billion
# Other Major Contributors:
# Regional Party spent $6.21 billion closely followed by INC with $6.06 billion.
# AAP spent the least among the listed parties, totaling $5.86 billion.
# Spending Distribution:
# The campaign spending is fairly balanced among all four parties, with each party contributing roughly one-fourth of the total spending.
# This indicates a competitive campaign environment, with substantial investments by all major participants.

# Insights:
# The slight differences in spending may reflect strategic allocation to key states or channels.
# Parties with higher spending might have invested in more outreach programs, advertisements, or events to influence voter engagement.
# Such data can help in assessing campaign intensity and resource utilization across parties.

In [47]:
# Statewise total spending

state_spending = df.groupby('state')['spend'].sum().reset_index()
print(state_spending)

         state       spend
0        Bihar  6080198886
1  Maharashtra  6028715204
2   Tamil Nadu  6422381850
3           UP  6706158360

In [65]:
# Statewise AVERAGE spending

state_spending = df.groupby('state')['spend'].mean().reset_index()
print(state_spending)

         state         spend
0        Bihar  4.931224e+06
1  Maharashtra  5.011401e+06
2   Tamil Nadu  5.162686e+06
3           UP  5.080423e+06

In [61]:
state_spending_sorted = state_spending.sort_values(by="spend", ascending=False)
print(state_spending_sorted)

         state         spend
2   Tamil Nadu  5.162686e+06
3           UP  5.080423e+06
1  Maharashtra  5.011401e+06
0        Bihar  4.931224e+06

In [ ]:
# Highest Spending:
# Uttar Pradesh (UP) received the highest campaign spending, totaling approximately $6.60 billion. This indicates that parties heavily invested
# resources in this state, likely due to its large voter base and political significance.
# Moderate Spending:
# Tamil Nadu had the second-highest spending at $6.32 billion, followed by Bihar with $5.95 billion. These states also represent strategically 
# important regions for the campaign.
# Lowest Spending:
# Maharashtra recorded the lowest among the four states at $5.88 billion, though the amount is still substantial.
# Balanced Investment:
# The difference in spending across the states is not extreme, suggesting that parties aimed for a relatively balanced distribution of campaign
# resources across key regions.

# Insights for Strategic Decision Making:

In [ ]:
Resource Allocation: The higher spending in UP and Tamil Nadu reflects targeted resource allocation in states with higher voter turnout
or competitive constituencies.
Campaign Prioritization: Parties may have prioritized states based on electoral significance, past performance, or voter density.
Efficiency Analysis: Comparing spending with votes gained or seats won in each state could provide deeper insight into campaign ROI and effectiveness
of resource utilization.

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   campaign_id  5000 non-null   int64
 1   party        5000 non-null   object
 2   state        5000 non-null   object
 3   spend        5000 non-null   int64
 4   date         5000 non-null   object
dtypes: int64(2), object(3)
memory usage: 195.4+ KB

In [48]:
df['spend'] = df['spend'].astype(int)

In [51]:
df.to_csv("clean_campaign_spending.csv", index=False)

In [52]:
df=pd.read_csv('clean_campaign_spending.csv')
df

      campaign_id           party        state    spend        date
0               1             INC           UP  6388720  2025-12-09
1               2             INC   Tamil Nadu  8595779  2025-09-19
2               3             BJP  Maharashtra  7522730  2025-08-29
3               4             BJP           UP  3933796  2025-05-21
4               5             INC        Bihar  5618958  2025-04-09
...           ...             ...          ...      ...         ...
4995         4996             INC   Tamil Nadu  2729262  2025-11-16
4996         4997             INC  Maharashtra  1864885  2026-02-07
4997         4998             INC  Maharashtra  5418805  2026-02-03
4998         4999  Regional Party           UP  4948501  2025-10-10
4999         5000             BJP   Tamil Nadu  8594551  2026-02-09

[5000 rows x 5 columns]

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   campaign_id  5000 non-null   int64
 1   party        5000 non-null   object
 2   state        5000 non-null   object
 3   spend        5000 non-null   int64
 4   date         5000 non-null   object
dtypes: int64(2), object(3)
memory usage: 195.4+ KB

In [55]:
# Partywise total spending
party_spending = df.groupby('party')['spend'].sum().reset_index()
print(party_spending)

            party       spend
0             AAP  5974583368
1             BJP  6711070320
2             INC  6242487826
3  Regional Party  6309312786