In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Candidates.csv")
df

      candidate_id                  name           party  age     education
0                1          Neelima Bala  Regional Party   65           PhD
1                2   Siddharth Prabhakar             AAP   49           PhD
2                3              Sai Dora             BJP   53  Postgraduate
3                4          Bhavika Kale             AAP   30      Graduate
4                5        Upadhriti Guha             BJP   33      Graduate
...            ...                   ...             ...  ...           ...
2995          2996          Zayyan Palla  Regional Party   50     12th Pass
2996          2997        Bhavika Sarraf             AAP   42  Postgraduate
2997          2998  Luke Balasubramanian  Regional Party   26      Graduate
2998          2999       Aarush Srinivas     Independent   30  Postgraduate
2999          3000        Dhriti Chandra             INC   47     12th Pass

[3000 rows x 5 columns]

In [3]:
df.head()

   candidate_id                 name           party  age     education
0             1         Neelima Bala  Regional Party   65           PhD
1             2  Siddharth Prabhakar             AAP   49           PhD
2             3             Sai Dora             BJP   53  Postgraduate
3             4         Bhavika Kale             AAP   30      Graduate
4             5       Upadhriti Guha             BJP   33      Graduate

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   candidate_id  3000 non-null   int64
 1   name          3000 non-null   object
 2   party         3000 non-null   object
 3   age           3000 non-null   int64
 4   education     3000 non-null   object
dtypes: int64(2), object(3)
memory usage: 117.3+ KB

In [5]:
df.shape

(3000, 5)

In [6]:
# checking Duplicated values
df.duplicated().sum()

np.int64(0)

In [7]:
df.dtypes

candidate_id     int64
name            object
party           object
age              int64
education       object
dtype: object

In [14]:
df["party"]

0       Regional Party
1                  AAP
2                  BJP
3                  AAP
4                  BJP
             ...
2995    Regional Party
2996               AAP
2997    Regional Party
2998       Independent
2999               INC
Name: party, Length: 3000, dtype: object