In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Social_Media.csv")
df

,post_id,party,platform,likes,shares,sentiment,date
0,1,INC,Instagram,7079.0,1605,Positive,2025-04-12
1,2,AAP,Instagram,38.0,257,Neutral,2025-12-10
2,3,INC,Facebook,4554.0,4828,Negative,2026-01-17
3,4,Regional Party,Instagram,4954.0,392,Positive,2026-01-23
4,5,BJP,Facebook,7459.0,4658,Neutral,2026-02-07
...,...,...,...,...,...,...,...
49995,49996,BJP,Twitter,211.0,311,Negative,2025-07-07
49996,49997,INC,Facebook,347.0,4296,Neutral,2026-01-02
49997,49998,AAP,Twitter,1997.0,2451,Positive,2025-04-26
49998,49999,AAP,Facebook,9570.0,2480,Negative,2025-09-30
49999,50000,INC,Facebook,7751.0,2502,Neutral,2025-08-14

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   post_id    50000 non-null  int64
 1   party      50000 non-null  object
 2   platform   50000 non-null  object
 3   likes      49000 non-null  float64
 4   shares     50000 non-null  int64
 5   sentiment  50000 non-null  object
 6   date       50000 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 2.7+ MB

In [6]:
# Handle null Values Using fillna
df["likes"] = df["likes"].fillna(df["likes"].median())

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   post_id    50000 non-null  int64
 1   party      50000 non-null  object
 2   platform   50000 non-null  object
 3   likes      50000 non-null  float64
 4   shares     50000 non-null  int64
 5   sentiment  50000 non-null  object
 6   date       50000 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 2.7+ MB

In [8]:
# change datatype
# change data type 
df['likes'] = df['likes'].astype(int)
df['date'] = pd.to_datetime(df['date'])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   post_id    50000 non-null  int64
 1   party      50000 non-null  object
 2   platform   50000 non-null  object
 3   likes      50000 non-null  int64
 4   shares     50000 non-null  int64
 5   sentiment  50000 non-null  object
 6   date       50000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 2.7+ MB

In [10]:
# save data
df.to_csv("clean_social_media.csv", index=False)

In [11]:
# checking data
df=pd.read_csv("clean_social_media.csv")
df

       post_id           party   platform  likes  shares sentiment        date
0            1             INC  Instagram   7079    1605  Positive  2025-04-12
1            2             AAP  Instagram     38     257   Neutral  2025-12-10
2            3             INC   Facebook   4554    4828  Negative  2026-01-17
3            4  Regional Party  Instagram   4954     392  Positive  2026-01-23
4            5             BJP   Facebook   7459    4658   Neutral  2026-02-07
...        ...             ...        ...    ...     ...       ...         ...
49995    49996             BJP    Twitter    211     311  Negative  2025-07-07
49996    49997             INC   Facebook    347    4296   Neutral  2026-01-02
49997    49998             AAP    Twitter   1997    2451  Positive  2025-04-26
49998    49999             AAP   Facebook   9570    2480  Negative  2025-09-30
49999    50000             INC   Facebook   7751    2502   Neutral  2025-08-14

[50000 rows x 7 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   post_id    50000 non-null  int64
 1   party      50000 non-null  object
 2   platform   50000 non-null  object
 3   likes      50000 non-null  int64
 4   shares     50000 non-null  int64
 5   sentiment  50000 non-null  object
 6   date       50000 non-null  object
dtypes: int64(3), object(4)
memory usage: 2.7+ MB