In [1]:
import pandas as pd
import numpy as np

# No need to Clean Data is Already Clean

In [2]:
df=pd.read_csv("Constituencies.csv")
df

     constituency_id        state constituency_name  total_voters
0                  1    Rajasthan             Avadi        758713
1                  2    Karnataka           Katihar        913551
2                  3   Tamil Nadu          Phagwara       2445578
3                  4    Karnataka          Bhatpara        175957
4                  5      Gujarat      North Dumdum       2808470
..               ...          ...               ...           ...
538              539   Tamil Nadu           Gurgaon       1693608
539              540  Maharashtra             Sikar       2446204
540              541    Karnataka            Howrah        873860
541              542      Gujarat          Parbhani       1111643
542              543           UP            Etawah       1561618

[543 rows x 4 columns]

In [3]:
df.dtypes

constituency_id       int64
state                object
constituency_name    object
total_voters          int64
dtype: object

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 543 entries, 0 to 542
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   constituency_id    543 non-null    int64
 1   state              543 non-null    object
 2   constituency_name  543 non-null    object
 3   total_voters       543 non-null    int64
dtypes: int64(2), object(2)
memory usage: 17.1+ KB

In [5]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# data is clean no need to clean

In [6]:
df.head()

   constituency_id       state constituency_name  total_voters
0                1   Rajasthan             Avadi        758713
1                2   Karnataka           Katihar        913551
2                3  Tamil Nadu          Phagwara       2445578
3                4   Karnataka          Bhatpara        175957
4                5     Gujarat      North Dumdum       2808470